name: publish

on:
  push:
    branches: [main]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: node -v
      - name: Build Demo ğŸ› ï¸
        run: |
          npm install
          cd demo
          npm install
          npx papua build
      - name: Deploy Demo ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: publish
          folder: demo/dist
          target-folder: demo
      - name: Build Docs ğŸ› ï¸
        run: |
          npm install
          cd doc
          npm install
          npx papua build
      - name: Deploy Docs ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: publish
          folder: doc/dist
          target-folder: doc
